### ISSUE TITLE
Wrench durability does not decrease

### ISSUE THREAD

**Issue by discoguillotine** [CreeperMagnet/the-creepers-code#101]
During development, wrench durability was removed, but during the process of re-adding it, something was done improperly. Durability shows in lore but does not go down.

**Comment by HingeDH** [comment]
Wrench durability was re-added due to the mending and unbreaking enchantments. The bug here is actually that the durability does not decrease

**Comment by CreeperMagnet** [comment]
Works as intended

**Comment by CreeperMagnet** [comment]
Fixed in V1.0.1.
