### ISSUE TITLE
Description in pack.mcmeta shows wrong version as of 2.0

### ISSUE THREAD

**Issue by al-beqaa** [CreeperMagnet/the-creepers-code#112]
What the fuck is wrong with you?

Don't you realize your actions have consequences? Every man's heart one day beats its final beat. His lungs breathe their final breath. And if what that man did in his life makes the blood pulse through the body of others and makes them bleed deeper in something that's larger than life, then his essence, his spirit, will be immortalized by the storytellers. This little mistake ensured you will never know what that's like. So pick a god and pray. Because I'm coming for you.

**Comment by CreeperMagnet** [comment]
Working as intended, you simply do not understand my ways. My goals are beyond your understanding.
