### ISSUE TITLE
teapot is invisible and holding a invisibility potion

### ISSUE THREAD

**Issue by Verfont2** [CreeperMagnet/the-creepers-code#120]
i decided to get a teapot then placed it, the next minecraft day it became invisible and stays invisible now
![Screenshot (71)](https://user-images.githubusercontent.com/107367032/173248752-1283cfe1-2b0b-4bbd-85fe-b7dd84d8625d.png)

**Comment by CreeperMagnet** [comment]
Join our discord so we can assess your issue in real time.

https://discord.gg/J3AtMSW

**Comment by Verfont2** [comment]
> Join our discord so we can assess your issue in real time.
> 
> https://discord.gg/J3AtMSW

already in it user:star flatinum

**Comment by CreeperMagnet** [comment]
Closed issue as invalid. Reporter is using a paper server client.
