### ISSUE TITLE
advancements.tcc.minecraft.adventure.obtain_locket_of_learning.description is inconsistent with the vanilla lang file (en_us)

### ISSUE THREAD

**Issue by BemusedLeader10** [CreeperMagnet/the-creepers-code#128]
"advancements.tcc.minecraft.adventure.obtain_locket_of_learning.description": "Obtain a useful enchanting tool from the basement of a woodland mansion and use it to store some XP"

It always refers to XP as experience points and not the abbreviation.

**Comment by CreeperMagnet** [comment]
Can you give us a more clear description maybe?

**Comment by BemusedLeader10** [comment]
Should just be
"advancements.tcc.minecraft.adventure.obtain_locket_of_learning.description": "Obtain a useful enchanting tool from the basement of a woodland mansion and use it to store some experience points"

**Comment by CreeperMagnet** [comment]
Noted—XP ----> experience points

**Comment by CreeperMagnet** [comment]
Fixed in the next version.
