### ISSUE TITLE
Frostbloom has chance of growing into Spruce trees

### ISSUE THREAD

**Issue by Booooonk** [CreeperMagnet/the-creepers-code#130]
When using bonemeal on frostblooms, there is an extremely low chance that the frostbloom will actually grow into a full Spruce tree, which becomes more common when you up the randomTickSpeed. Looking at the functions and what I can figure out empirically I'm guessing it has something to do with when the sapling passes a bonemeal forced growth check and a natural growth check passes before the function can reset the growth state of the frostbloom, which is possible because of the Java edition's default randomTickSpeed of 3, meaning that though rare, it is possible for the frostbloom spruce sapling to be selected more than once. Theoretically, this would also mean that setting randomTickSpeed to 1 should solve this, but this would greatly limit how players can customize the game experience with the data pack installed. Not super into data pack making so I don't really have a suggested fix method.

The problem with replicating this is with the default randomTickSpeed of 3, replication can take anywhere from ten seconds to ten minutes. I have naturally encountered this in a survival world twice, and multiple times afterward on creative test worlds. Basically with the bonemeal in either hand, just hold the use button down on a non-obstructed frostbloom until it eventually grows. For a more dramatic demonstration, turn randomTickSpeed extremely high (like 4096) and the frostbloom can even grow by itself. 

All testing was done on vanilla client 1.19 with no other data packs installed other than latest version of TCC.

Helpful Articles:
https://minecraft.fandom.com/wiki/Tree
https://minecraft.fandom.com/wiki/Tick#Random_tick

**Comment by Booooonk** [comment]
(Suggestion from testing) Dark oak sapling has the unique property of being unable to be grown unless placed in a 2x2 formation. However, bonemeal usage can still put it at stage=1 (just not into a grown tree), so part of detecting whether the sapling has grown by relying on its stage should still work. The only problem is you'd probably have to have some sort of lore explanation for why they can't be placed next to each other or other saplings preferably.

**Comment by CreeperMagnet** [comment]
Fixed in the next version. Simply placed a level 0 light block above the spruce sapling.
