### ISSUE TITLE
How to craft boomerang/get it, and Eye Of Chronos

### ISSUE THREAD

**Issue by BrunoUzbolt** [CreeperMagnet/the-creepers-code#132]
Hello, this isn't really an issue I am just wondering something. My friend installed the data pack and I have been loving is so far, but there's 1 thing thats on my mind. When we killed the Wraith I believe it was, I got the Eye of Chronos. Now I don't know if it's just a clock or it can do something, and it doesn't say anything in the wiki so, I'm wondering if it does something other than being a clock. And about the boomerang, how can I get it? Is there like a craft for it or?

**Comment by tacozyt** [comment]
Boomerang is craftable:
LPP
   P
   L

**Comment by tacozyt** [comment]
L = Leather
P = Planks
X = Nothing

**Comment by CreeperMagnet** [comment]
This is not the place for questions. The "Eye of Chronos" and "Wraith" don't even exist in this datapack. Please join our discord or reddit for support with this.

This is not an issue. Closed.

**Comment by tacozyt** [comment]
To check all the crafts please see the compendium!! @BrunoUzbolt
