### ISSUE TITLE
TCC texture conflicting with another datapack

### ISSUE THREAD

**Issue by MeiaQuatru** [CreeperMagnet/the-creepers-code#140]
I was testing datapacks to play with my friends on 1.19.2 and noticing that the [Thirts Water](https://www.planetminecraft.com/data-pack/thirstwater-datapack-new-mechanic/) texture breaks when the TCC texture is with higher priority, the problem could be solved if I lower the TCC texture priority, but some textures don't work as they should, an example is the rings and Witch Hat

https://imgur.com/tjyYYdG.png

**Comment by Ellivers** [comment]
Overlapping packs not working is not a TCC issue, use a resource pack merging tool such as [Mitochondria](https://mito.thenuclearnexus.live/).

**Comment by dragonflame86** [comment]
Use mitochondria, this isn't a TCC issue. Datapacks with resources will conflict unless merged with a merger like mitochondria.
