### ISSUE TITLE
Piglin bartering loot table action dependent on HOW Piglin receives gold ingot

### ISSUE THREAD

**Issue by IsaacPassmore** [CreeperMagnet/the-creepers-code#141]
I like the addition of considering how much gold the player is wearing to determine which loot table the piglin uses to barter from. However, the piglin uses different loot tables depending on how the player gives gold to the piglin. This is undesirable behavior as it makes automating piglin barting significantly more difficult and requires the player to constantly interact with the piglin rather than simply be near the piglin to receive the loot. The piglin should use the same loot table regardless of whether or not the player throws or hands the gold ingot to the piglin. For reference, it appears that the desired loot table is used when the player hands the gold ingot to the piglin. Otherwise, it does not appear that the piglin looks up the correct loot table based on the gold worn by the player.

Code located here third-to-last and second-to-last lines are what this issue in aimed to address: 
the-creepers-code/datapack/data/tcc/functions/entity/piglin/trading/set_score.mcfunction

Desired changes: line 12 should be similar to line 11.

`############################################################
# Runs code for bartering
############################################################

scoreboard players set #temp_0 tcc.dummy 0
execute if predicate tcc:entity/wearing/gold_equipment/golden_helmet run scoreboard players add #temp_0 tcc.dummy 1
execute if predicate tcc:entity/wearing/gold_equipment/golden_chestplate run scoreboard players add #temp_0 tcc.dummy 1
execute if predicate tcc:entity/wearing/gold_equipment/golden_leggings run scoreboard players add #temp_0 tcc.dummy 1
execute if predicate tcc:entity/wearing/gold_equipment/golden_boots run scoreboard players add #temp_0 tcc.dummy 1
execute if predicate tcc:entity/wearing/gold_equipment/golden_ring run scoreboard players add #temp_0 tcc.dummy 1
execute if entity @s[advancements={tcc:technical/multiple_trigger_types/trade_with_piglin={interact=true}}] as @e[type=piglin,tag=!smithed.strict,limit=1,sort=nearest,distance=..20,nbt={Brain:{memories:{"minecraft:admiring_item":{ttl:120L,value:1b}}},HandItems:[{},{id:"minecraft:gold_ingot"}]}] run function tcc:entity/piglin/trading/as_entity
execute if entity @s[advancements={tcc:technical/multiple_trigger_types/trade_with_piglin={throw=true}}] as @e[type=piglin,tag=!smithed.strict,limit=1,sort=nearest,distance=..20,nbt={Brain:{memories:{"minecraft:admiring_item":{value:1b}}}}] unless data entity @s HandItems[1].id run function tcc:entity/piglin/trading/as_entity
advancement revoke @s only tcc:technical/multiple_trigger_types/trade_with_piglin`

**Comment by Ellivers** [comment]
Not sure what you are talking about. Both giving and throwing a gold ingot to a piglin triggers this function. There is only one loot table, which gives the appropriate loot depending on what the player was wearing.
