### ISSUE TITLE
Frostbloom does not generate correctly

### ISSUE THREAD

**Issue by Booooonk** [CreeperMagnet/the-creepers-code#159]
Tested with 1.19.4 Vanilla client
Haven't tried in survival mode yet, but when tping to tundra keep via /locate and /tp the frostblooms doesn't generate properly, becoming a normal spruce sapling and a tiny sideway frostbloom model. Frostbloom placed down from the item works normally.

**Comment by CreeperMagnet** [comment]
confirmed, this is because we forgot to update to display entities

**Comment by CreeperMagnet** [comment]
Fixed in the next version.
