### ISSUE TITLE
How configurable is your modpack-in-a-datapack?

### ISSUE THREAD

**Issue by allanonmage** [CreeperMagnet/the-creepers-code#209]
I stumbled across your datapack on Modrinth, and there's a lot of good stuff in there.  However, some of the things I've already planned to include in my modpack via other mods or datapacks.  Can yours have certain things turned off?  Or, for the structures, be additive instead of replacing the vanilla ones?

For example, I like Yung's structures, and I'd rather not have your monument overwrite it since they are very similar.  There's a biome mod that I like that has a revamped Woodland Mansion too.  And Repurposed Structures will reuse both Yung's structures, and the ones from that datapack whose name escapes me.

Also, I haven't found a good way to integrate more difficult pillagers with vanilla raid farms, so I usually turn off some of the pillager themes things.

**Comment by CreeperMagnet** [comment]
This is not the place for questions. Go to our discord. There is no configuration file, this is a datapack.

**Comment by allanonmage** [comment]
Discord has never let me use my account in the 10 years or so that I've had it, so this is what I've got.
