### ISSUE TITLE
Some blocks can't be painted with a the paintbrush

### ISSUE THREAD

**Issue by Magnogen** [CreeperMagnet/the-creepers-code#210]
Beds (might be because its two blocks), and banners (might be because its got a load of nbt, so im not sure if it should be included anyway) can't be painted by the paintbrush

**Comment by CreeperMagnet** [comment]
Beds are a technical limitation.

Banners are not redyeable by design, they have a unique pattern system which isn't like any of the other redyeable blocks. 

(Think of how odd it'd be to suddenly change the base color of a banner but none of the pattern colors.)

**Comment by CreeperMagnet** [comment]
No matter what method you attempt to use to replace the bed, it always either spawns the other half as an item or creates particles and sound. 

Structure loading, jigsaw loading, fill, setblock—all of it.
