### ISSUE TITLE
"subtitles.tcc.entity.phantom_item_frame.break" Should change to be consistent with Vanilla

### ISSUE THREAD

**Issue by BemusedLeader10** [CreeperMagnet/the-creepers-code#213]
subtitles.tcc.entity.phantom_item_frame.break is translated as "Phantom Item Frame breaks", but item frames and glow item frames are translated as "Item Frame broken" and "Glow Item Frame broken".

Please change the English translation to "Phantom Item Frame broken"

**Comment by CreeperMagnet** [comment]
Fixed in the next version.
