### ISSUE TITLE
Boomerangs don't interact correctly with Endermen

### ISSUE THREAD

**Issue by al-beqaa** [CreeperMagnet/the-creepers-code#215]
- The simulated teleportation to get the Endermen away from the boomerang seems to use the basic /spreadplayers, so if you attack one in a cave or in the Nether it teleports alllll the way up
- Anger isn't triggered at all; this should be easy to implement now since [this bug](https://bugs.mojang.com/browse/MC-188506) was fixed

monkey throw boomerang, but boomerang no boom on ender monkey

**Comment by CreeperMagnet** [comment]
Turns out it doesn't use the basic spreadplayers, but it uses spreadplayers under 128, which is just barely enough to include the nether roof. I've lowered it to 120.

For the aggro, I've decided not to include it since:
1. All vanilla projectiles do not trigger aggro
2. I am lazy

**Comment by al-beqaa** [comment]
you could read the y pos of the enderman into storage and use a macro for the spreadplayers instead of a fixed value :trollface:

**Comment by CreeperMagnet** [comment]
see point 2
