### ISSUE TITLE
Captains in outposts have the chilling banner and don't give bad omen or drop an ominous bottle

### ISSUE THREAD

**Issue by miniera2** [CreeperMagnet/the-creepers-code#220]
![2024-04-30_00 37 49](https://github.com/CreeperMagnet/the-creepers-code/assets/91031737/c1750c38-52cf-4672-8866-b9427ea80e4b)

Captains in outposts have the chilling banner and don't give bad omen or drop an ominous bottle if the 1.21 pack is enabled, I don't know if the same happens with patrols.

Tested in vanilla 1.20.5 with version 1.3.4

**Comment by CreeperMagnet** [comment]
Thanks for the report—this was fixed on dev but got put on the wrong branch. I'm pushing a release to fix this within the next hour.
