### ISSUE TITLE
The tangling pearl teleports items before other data packs can edit them, causing compatibility issues

### ISSUE THREAD

**Issue by edayot** [CreeperMagnet/the-creepers-code#249]
Linked issue : https://github.com/edayot/SimpleDrawer/issues/34

Looking at the code, it happens when tcc is ticking before simpledrawer, and teleporting the item before simpledrawer can handle it.

Step by step explanation of the problem : 
- Minecraft spawn the item
- TCC is ticking and teleport it away
- Simpledrawer handle block breaking and fail to access it
- Simpledrawer spawn a new item containing the drawer
- The player gets the base item (in my case beehive) and the drawer item

~~I don't know how to fix the compatibility issue though.~~

**Comment by edayot** [comment]
A possible fix is to wait for 1 or 2 ticks to let others datapack do what they want with the item before teleporting it away.

**Comment by Ellivers** [comment]
Or SimpleDrawer could add a tag to let other data packs know that the item shouldn't be messed with (`smithed.entity`). TCC does not teleport any items with this tag.
