### ISSUE TITLE
Shift-Clicking a recipe output item gives you recipe output as single, unstackable items

### ISSUE THREAD

**Issue by Bonniethebunny-hub** [CreeperMagnet/the-creepers-code#49]
When using the stonecutter to create amethyst gems, I tried shiftclicking the recipe output to fasten the crafting process. This filled my inventory with the recipe output items, which were unstackable.

**Comment by CreeperMagnet** [comment]
This is due to a Mojang bug, [MC-65198](https://bugs.mojang.com/browse/MC-65198).

This can be fixed by reverting the stonecutter recipe to its previous state without any additional checks, which will naturally cause errors with give all recipe packs once again.

**Comment by CreeperMagnet** [comment]
Fixed in V0.5 Beta 8.
