### ISSUE TITLE
Wrenches still consume durability when right-clicking rotatable blocks in their unrotatable states

### ISSUE THREAD

**Issue by ChromaKey81** [CreeperMagnet/the-creepers-code#75]
Still consumes durability and plays sound

**Comment by ChromaKey81** [comment]
https://user-images.githubusercontent.com/66658267/123529738-4b94b080-d6c1-11eb-9623-f5e2e4e7ba26.mp4

**Comment by ChromaKey81** [comment]
This is also the case with hoppers. The common trait here is that both of them have the `facing` block state but don't have all six options usually available to blocks with that state

**Comment by CreeperMagnet** [comment]
Again, the description for this bug is massively incorrect.

**Comment by CreeperMagnet** [comment]
Fixed in the next version.
