### ISSUE TITLE
10 second clock causing 500ms lagspike

### ISSUE THREAD

**Issue by Justsnoopy30** [CreeperMagnet/the-creepers-code#84]
TCC is causing a ~500ms lagspike every ten seconds when it runs its technical:ten_second_clock function
I've narrowed it to the ocean monuments command in the file at line 13: `execute unless data storage tcc:storage root.gamerules{generateMonuments:0b} as @a[predicate=tcc:in_ocean] at @s positioned ~ ~-64 ~ unless entity @e[type=marker,tag=tcc.monument,distance=..128] positioned ~ ~64 ~ run function tcc:worldgen/ocean_monument_edits/detect/check_storage1`
This happens every 10 seconds regardless of if anyone is near an ocean monument or generating new chunks.

**Comment by CreeperMagnet** [comment]
Fixed in the next version.
