### ISSUE TITLE
Minecraft Version

### ISSUE THREAD

**Issue by ChopsKingsland** [CreeperMagnet/the-creepers-code#85]
Just wondering, does this only work on 1.17, or can I use it on 1.16.5?

**Comment by CreeperMagnet** [comment]
You can use the older version of V0.4 at this release page: https://github.com/CreeperMagnet/the-creepers-code/releases/tag/V0.4

It will not have the newer V0.5 features. Cry about it.

**Comment by ChopsKingsland** [comment]
Is there a list of v0.4 features?

**Comment by CreeperMagnet** [comment]
Also, this page is for bugs and bugs only. Making an issue to ask what Minecraft Version the pack runs on is not an acceptable use of this page.

**Comment by CreeperMagnet** [comment]
> Is there a list of v0.4 features?

It's literally just everything **but** the V0.5 features. I'm not putting in the effort to make a list for you.

**Comment by ChopsKingsland** [comment]
Ok, thaknk you
