### ISSUE TITLE
Candles and Carpets are undyeable

### ISSUE THREAD

**Issue by barraIhsan** [CreeperMagnet/the-creepers-code#86]
So candles and carpets cannot be dyed. So I go to the code, and there is nothing wrong. When I stand on candle/carpet and run `/function tcc:item/paintbrush/color_block/blue` it worked. But when I right-click it with a paintbrush, nothing happened. When I see the block tags for candles and carpet. Suddenly there are `#tcc:raycast_ignore` block tags in carpet and candles. Yes, it will make sense to ignore it. But it disallows us to dye carpets and candles.

So I try to make a new file in the `data/tcc/tags/blocks/paintbrush/raycast_ignore.json` with the same file as the original `raycast_ignore.json` unless I removed the candles and the carpets. And also I try to change all `#tcc:raycast_ignore` to `#tcc:paintbrush/raycast_ignore` in the `data\tcc\functions\item\paintbrush\raycast.mcfunction`. Yes, it will work. But now the problem is you cannot dye the block under the candles.

**Comment by ChromaKey81** [comment]
will be fixed in next patch
