### ISSUE TITLE
Block Breaker sometimes requires manual placement to work after opening world

### ISSUE THREAD

**Issue by ncfumction** [CreeperMagnet/the-creepers-code#90]
Upon further inspection, it seems like this is because of async entity loading. The scheduled function runs when entities are not loaded, thus cannot target the marker armor stand.

Solution: ~~scoreboard timer~~ When the dropper is powered, schedule a function to remove the schedule tag regardless of the tag exists or not, which also clear itself

**Comment by Ellivers** [comment]
Fixed in the next update
