### ISSUE TITLE
This is not an issue, but more of an suggestion

### ISSUE THREAD

**Issue by flagz404** [CreeperMagnet/the-creepers-code#92]
Hi!
I just found out about `The Creeper's Code` and it's really cool!
I just have some suggestions for this pack!

**1.** Maybe adding spawn anchors, but for _The End_?
**2.** Custom exit screen, I'll make a pull request if you approve this 2nd suggestion :>
**3.** Bucket of ice cream using `custommodeldata` for bread

That's all I can think of... Thank you for reading (if you read this, of course)

**Comment by PrancerMane** [comment]
Hello this github is not meant for suggestion but rather the discord. Also those ideas are most likely going to get denied because it doesn't fit I with creepers philosophy.Please use the discord rather than the github in the future

**Comment by CreeperMagnet** [comment]
If it is not an issue, it does not belong here. End of story. These suggestions are not relevant here, nor will they be added.
